### ISSUE TITLE
How to invoke the new http_status_reply for unusual statuses

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplwebtut#16]
Throwing divide by zero or soemthing will generate 500, and no handler will generate 404, but what about something like 403 forbidden?

My impression is that there's some exception I can throw?

**Comment by Anniepoo** [comment]
Assigning to Jan to get clarity.  Then annie will fix.

**Comment by JanWielemaker** [comment]
There are two replies: throw(http_reply(Term)), where Term is handed to 
http://www.swi-prolog.org/pldoc/man?predicate=http_status_reply/4, which isn't very well documented :(  The source should be pretty clear though :)

The other is to formulate a normal reply (the way you do for 200) and add a header the usual
way:

    format('Status: 403 forbidden~n')

Thus, for a normal CGI-style response the system will add 200 OK if there is no status header
and the provided one otherwise.

**Comment by wouterbeek** [comment]
@Anniepoo Where did you find a predicate named `http_status_page`?

**Comment by Anniepoo** [comment]
closed fixed
