### ISSUE TITLE
Http paths, are they still collected to cache, with make only? 

### ISSUE THREAD

**Issue by xpxaxsxi** [Anniepoo/swiplwebtut#18]
It is so, that when doing a Compile Buffer (ctrl-C ctrl-B)  in Emacs, the http:location/3-facts that were changed by a programmer, they are not recognized.

When changing http:location/3-facts, programmer needs to do a make/0.   Sometimes it makes the whole Prolog- development system, many screenfuls of results. 

I am not 100% sure, but documentation does not explicitly say that make/0 is needed to parse the http:location/3-facts. Could it be possible to parse the paths with Compile Buffer also?

**Comment by Anniepoo** [comment]
I don't know why it's making your entire dev system. I've never seen that behavior.
I use make/0

**Comment by JanWielemaker** [comment]
Why the dev system is reloaded by a make/0 is indeed the good question.  Are you using a saved state of some sort?  Are you on Windows and the system went through a daylight saving time change
since its installation (there have been issues with that, not sure about the current status)?  If you are using Windows you may consider reinstalling.  If you start Prolog and type `?- make.` nothing should be loaded.

FYI, the path declarations are compiled to a representation that speeds up mapping a location to a handler.  The cache listens to a message from make/0 to clear itself, so it is rebuilt on the next request. See the very end of `library(http/http_dispatch)`.

**Comment by xpxaxsxi** [comment]
Possibly it was some Windows 10 system malfunction :)
